#ifndef _VECTOT_IMPL_H_
#define _VECTOT_IMPL_H_

#include "./header/vector_copy.h"
#include "./header/vector_print.h"
#include "./header/vector_expand.h"
#include "./header/vector_insert.h"
#include "./header/vector_remove.h"
#include "./header/vector_delete.h"
#include "./header/vector_find.h"
#include "./header/vector_pushback.h"
#include "./header/vector_popback.h"
#include "./header/vector_deduplicate.h"
#include "./header/vector_shrunk.h"
#include "./header/vector_replace.h"
#include "./header/vector_traverse.h"
#include "./header/vector_increase.h"
#include "./header/vector_sort.h"
#include "./header/vector_bubblesort.h"
#include "./header/vector_disorder.h"
#include "./header/vector_uniquify.h"
#include "./header/vector_uniquify1.h"
#include "./header/vector_search.h"
#include "./header/.vector_binsearch"
#endif
